version: "3.7"

services:
  example:
    container_name: example
    build:
      context: ../kotlin/example
      dockerfile: example-dockerfile
  identity:
    container_name: identity
    build:
      context: ../kotlin/identity
      dockerfile: identity-dockerfile
  gateway:
    container_name: gateway
    build:
      context: ../kotlin/gateway/
      dockerfile: gateway-dockerfile
    ports:
      - 8080:8080
